####################################################################################
# List of available effects:                                                       #
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html #
####################################################################################

gui-name: "&aNazwa gui"
no-money-message: "&cBrak srodkow na zakup."
successful-buy-message: "&aZakupiles efekt."
effects:
 default: 
  icon: "276 1 name:&c&6Sila_1 lore:&c_Cena>_10_blokow_emeraldow&nl&c_Czas>_100s"
  price: 10
  item: 133
  effect: "INCREASE_DAMAGE:10:2"
